name: Daily Dependency & Security Check

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch: {}   # Allows manual triggering

jobs:
  audit:
    name: Dependency & Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run security audit
        run: npm audit --json > audit.json

      - name: Check for vulnerabilities
        id: check_vuln
        run: |
          # Extract total vulnerabilities using jq
          VULN_COUNT=$(jq '.metadata.vulnerabilities.total' audit.json)
          echo "VULN_COUNT=$VULN_COUNT" >> $GITHUB_ENV
          echo "Total vulnerabilities: $VULN_COUNT"

      - name: Create GitHub issue if vulnerabilities found
        if: env.VULN_COUNT != '0'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'Dependency Vulnerabilities Found'
          content-filepath: audit.json
          labels: security, automated
